# Tutorial On Reading-In An R Dataset With Pandas Using [Pyreadr](https://pypi.org/project/pyreadr/)

### Install pyreadr

In [ ]:
!pip install pyreadr

### Imports

In [1]:
import pandas as pd
import pyreadr

### Reading In The RDA File

In [2]:
result = pyreadr.read_r("Data/R-Datasets/Car.rda") # also works for Rds, rda

# result is a dictionary where keys are the name of objects and the values python

### Get Name of Dictionary

In [3]:
print(result.keys())

odict_keys(['Car'])

### Creating a pandas DataFrame from the dictionary

In [4]:
df1 = result["Car"]
df1.head()

,choice,college,hsg2,coml5,type1,type2,type3,type4,type5,type6,...,cost3,cost4,cost5,cost6,station1,station2,station3,station4,station5,station6
rownames,,,,,,,,,,,,,,,,,,,,,
1,choice1,0.0,0.0,0.0,van,regcar,van,stwagon,van,truck,...,6.0,6.0,8.0,8.0,0.1,0.1,0.3,0.3,1.0,1.0
2,choice2,1.0,1.0,1.0,regcar,van,regcar,stwagon,regcar,truck,...,8.0,8.0,4.0,4.0,0.0,0.0,0.1,0.1,1.0,1.0
3,choice5,0.0,1.0,0.0,regcar,truck,regcar,van,regcar,stwagon,...,8.0,8.0,2.0,2.0,0.1,0.1,0.3,0.3,1.0,1.0
4,choice5,0.0,0.0,1.0,regcar,truck,regcar,van,regcar,stwagon,...,2.0,2.0,4.0,4.0,0.0,0.0,0.7,0.7,0.1,0.1
5,choice5,0.0,1.0,0.0,regcar,truck,regcar,van,regcar,stwagon,...,8.0,8.0,2.0,2.0,0.3,0.3,0.7,0.7,1.0,1.0

### You can see how many rows your data has

In [5]:
len(df1)

4654

### You can check the shape of your data

In [6]:
df1.shape

(4654, 70)

### Unless your screen is quite large, your output probably wonâ€™t display all 70 columns, let's change that!

In [7]:
pd.set_option("display.max.columns", None)
df1.head()

,choice,college,hsg2,coml5,type1,type2,type3,type4,type5,type6,fuel1,fuel2,fuel3,fuel4,fuel5,fuel6,price1,price2,price3,price4,price5,price6,range1,range2,range3,range4,range5,range6,acc1,acc2,acc3,acc4,acc5,acc6,speed1,speed2,speed3,speed4,speed5,speed6,pollution1,pollution2,pollution3,pollution4,pollution5,pollution6,size1,size2,size3,size4,size5,size6,space1,space2,space3,space4,space5,space6,cost1,cost2,cost3,cost4,cost5,cost6,station1,station2,station3,station4,station5,station6
rownames,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,choice1,0.0,0.0,0.0,van,regcar,van,stwagon,van,truck,cng,cng,electric,electric,gasoline,gasoline,4.175345,4.175345,4.817706,4.817706,5.138886,5.138886,250.0,250.0,400.0,400.0,250.0,250.0,4.0,4.0,6.0,6.0,2.5,2.5,95.0,95.0,110.0,110.0,140.0,140.0,0.6,0.6,0.25,0.25,0.50,0.50,3.0,3.0,2.0,2.0,3.0,3.0,0.7,0.7,1.0,1.0,1.0,1.0,4.0,4.0,6.0,6.0,8.0,8.0,0.1,0.1,0.3,0.3,1.0,1.0
2,choice2,1.0,1.0,1.0,regcar,van,regcar,stwagon,regcar,truck,methanol,methanol,cng,cng,gasoline,gasoline,3.310947,3.310947,3.586859,3.586859,4.414596,4.414596,125.0,125.0,300.0,300.0,300.0,300.0,2.5,2.5,4.0,4.0,6.0,6.0,85.0,85.0,140.0,140.0,95.0,95.0,0.0,0.0,0.40,0.40,0.25,0.25,3.0,3.0,3.0,3.0,2.0,2.0,0.7,0.7,1.0,1.0,1.0,1.0,4.0,4.0,8.0,8.0,4.0,4.0,0.0,0.0,0.1,0.1,1.0,1.0
3,choice5,0.0,1.0,0.0,regcar,truck,regcar,van,regcar,stwagon,cng,cng,electric,electric,gasoline,gasoline,4.039574,4.039574,2.777207,2.777207,3.282154,3.282154,300.0,300.0,250.0,250.0,300.0,300.0,6.0,6.0,2.5,2.5,4.0,4.0,140.0,140.0,85.0,85.0,95.0,95.0,0.1,0.1,0.40,0.40,0.75,0.75,2.0,2.0,3.0,3.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,6.0,6.0,8.0,8.0,2.0,2.0,0.1,0.1,0.3,0.3,1.0,1.0
4,choice5,0.0,0.0,1.0,regcar,truck,regcar,van,regcar,stwagon,methanol,methanol,cng,cng,electric,electric,7.065968,7.065968,7.387149,7.387149,5.460066,5.460066,200.0,200.0,75.0,75.0,300.0,300.0,4.0,4.0,6.0,6.0,2.5,2.5,100.0,100.0,85.0,85.0,95.0,95.0,0.0,0.0,0.25,0.25,0.60,0.60,2.0,2.0,3.0,3.0,3.0,3.0,1.0,1.0,0.7,0.7,1.0,1.0,8.0,8.0,2.0,2.0,4.0,4.0,0.0,0.0,0.7,0.7,0.1,0.1
5,choice5,0.0,1.0,0.0,regcar,truck,regcar,van,regcar,stwagon,cng,cng,electric,electric,gasoline,gasoline,5.794157,5.794157,6.345981,6.345981,4.690508,4.690508,75.0,75.0,300.0,300.0,350.0,350.0,4.0,4.0,6.0,6.0,2.5,2.5,85.0,85.0,95.0,95.0,110.0,110.0,0.1,0.1,0.40,0.40,0.75,0.75,1.0,1.0,2.0,2.0,3.0,3.0,0.7,0.7,1.0,1.0,1.0,1.0,6.0,6.0,8.0,8.0,2.0,2.0,0.3,0.3,0.7,0.7,1.0,1.0

### Showing Basics Statistics
Now that youâ€™ve seen what data types are in your dataset, itâ€™s time to get an overview of the values each column contains. You can do this with .describe():

In [8]:
df1.describe()

,college,hsg2,coml5,price1,price2,price3,price4,price5,price6,range1,range2,range3,range4,range5,range6,acc1,acc2,acc3,acc4,acc5,acc6,speed1,speed2,speed3,speed4,speed5,speed6,pollution1,pollution2,pollution3,pollution4,pollution5,pollution6,size1,size2,size3,size4,size5,size6,space1,space2,space3,space4,space5,space6,cost1,cost2,cost3,cost4,cost5,cost6,station1,station2,station3,station4,station5,station6
count,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.00000,4654.00000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.0,4654.0,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000,4654.000000
mean,0.768156,0.221960,0.357757,4.296262,4.296262,4.173241,4.173241,4.149952,4.149952,160.485604,160.485604,240.379244,240.379244,312.03266,312.03266,4.172540,4.172540,4.272991,4.272991,4.054469,4.054469,84.666953,84.666953,107.305544,107.305544,107.342071,107.342071,0.085260,0.085260,0.413666,0.413666,0.594059,0.594059,2.359046,2.359046,2.384401,2.384401,2.314353,2.314353,0.850774,0.850774,0.925677,0.925677,1.0,1.0,4.153846,4.153846,4.954448,4.954448,4.970348,4.970348,0.089514,0.089514,0.382768,0.382768,0.823915,0.823915
std,0.422055,0.415609,0.479392,1.912597,1.912597,1.909591,1.909591,1.863530,1.863530,70.698599,70.698599,92.920307,92.920307,39.61227,39.61227,1.390455,1.390455,1.462212,1.462212,1.439663,1.439663,23.044560,23.044560,20.956914,20.956914,20.544236,20.544236,0.174558,0.174558,0.203444,0.203444,0.265994,0.265994,0.785238,0.785238,0.796957,0.796957,0.785247,0.785247,0.150014,0.150014,0.129525,0.129525,0.0,0.0,2.648303,2.648303,2.233921,2.233921,2.229181,2.229181,0.190517,0.190517,0.253019,0.253019,0.327127,0.327127
min,0.000000,0.000000,0.000000,0.598726,0.598726,0.598726,0.598726,0.635196,0.635196,50.000000,50.000000,75.000000,75.000000,250.00000,250.00000,2.500000,2.500000,2.500000,2.500000,2.500000,2.500000,55.000000,55.000000,85.000000,85.000000,85.000000,85.000000,0.000000,0.000000,0.100000,0.100000,0.250000,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.700000,0.700000,0.700000,0.700000,1.0,1.0,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.100000,0.100000,0.100000,0.100000
25%,1.000000,0.000000,0.000000,3.086326,3.086326,2.993632,2.993632,2.907212,2.907212,125.000000,125.000000,250.000000,250.000000,300.00000,300.00000,2.500000,2.500000,2.500000,2.500000,2.500000,2.500000,65.000000,65.000000,85.000000,85.000000,95.000000,95.000000,0.000000,0.000000,0.250000,0.250000,0.400000,0.400000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.700000,0.700000,1.000000,1.000000,1.0,1.0,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.100000,0.100000,0.700000,0.700000
50%,1.000000,0.000000,0.000000,4.138683,4.138683,4.039574,4.039574,4.039574,4.039574,125.000000,125.000000,250.000000,250.000000,300.00000,300.00000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,85.000000,85.000000,95.000000,95.000000,95.000000,95.000000,0.000000,0.000000,0.400000,0.400000,0.600000,0.600000,3.000000,3.000000,3.000000,3.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,0.000000,0.000000,0.300000,0.300000,1.000000,1.000000
75%,1.000000,0.000000,1.000000,5.242332,5.242332,5.143528,5.143528,5.242332,5.242332,200.000000,200.000000,300.000000,300.000000,350.00000,350.00000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,100.000000,100.000000,140.000000,140.000000,110.000000,110.000000,0.100000,0.100000,0.600000,0.600000,0.750000,0.750000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0,8.000000,8.000000,6.000000,6.000000,6.000000,6.000000,0.100000,0.100000,0.700000,0.700000,1.000000,1.000000
max,1.000000,1.000000,1.000000,17.370563,17.370563,17.370563,17.370563,17.370563,17.370563,300.000000,300.000000,400.000000,400.000000,400.00000,400.00000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,0.600000,0.600000,0.750000,0.750000,1.000000,1.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,0.700000,0.700000,0.700000,0.700000,1.000000,1.000000

### While itâ€™s practical to see all the columns, you probably wonâ€™t need six decimal places, let's change it to two!

In [9]:
pd.set_option("display.precision", 2)
df1.tail()

,choice,college,hsg2,coml5,type1,type2,type3,type4,type5,type6,fuel1,fuel2,fuel3,fuel4,fuel5,fuel6,price1,price2,price3,price4,price5,price6,range1,range2,range3,range4,range5,range6,acc1,acc2,acc3,acc4,acc5,acc6,speed1,speed2,speed3,speed4,speed5,speed6,pollution1,pollution2,pollution3,pollution4,pollution5,pollution6,size1,size2,size3,size4,size5,size6,space1,space2,space3,space4,space5,space6,cost1,cost2,cost3,cost4,cost5,cost6,station1,station2,station3,station4,station5,station6
rownames,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4650,choice5,1.0,0.0,0.0,regcar,truck,regcar,van,regcar,stwagon,methanol,methanol,cng,cng,electric,electric,3.53,3.53,3.79,3.79,4.04,4.04,125.0,125.0,300.0,300.0,250.0,250.0,4.0,4.0,6.0,6.0,2.5,2.5,85.0,85.0,140.0,140.0,85.0,85.0,0.00,0.00,0.25,0.25,0.60,0.60,2.0,2.0,3.0,3.0,3.0,3.0,1.0,1.0,0.7,0.7,1.0,1.0,4.0,4.0,8.0,8.0,2.0,2.0,0.0,0.0,0.1,0.1,0.3,0.3
4651,choice3,0.0,1.0,0.0,regcar,truck,regcar,van,regcar,stwagon,cng,cng,electric,electric,gasoline,gasoline,3.09,3.09,3.56,3.56,3.80,3.80,75.0,75.0,300.0,300.0,350.0,350.0,2.5,2.5,4.0,4.0,6.0,6.0,95.0,95.0,110.0,110.0,140.0,140.0,0.25,0.25,0.60,0.60,1.00,1.00,3.0,3.0,3.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,4.0,4.0,6.0,6.0,0.1,0.1,0.3,0.3,1.0,1.0
4652,choice3,1.0,1.0,0.0,truck,van,truck,stwagon,truck,regcar,methanol,methanol,cng,cng,gasoline,gasoline,5.55,5.55,5.81,5.81,4.80,4.80,200.0,200.0,75.0,75.0,350.0,350.0,4.0,4.0,6.0,6.0,2.5,2.5,55.0,55.0,95.0,95.0,140.0,140.0,0.00,0.00,0.60,0.60,0.50,0.50,3.0,3.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,4.0,4.0,4.0,8.0,8.0,0.0,0.0,0.1,0.1,1.0,1.0
4653,choice3,1.0,0.0,0.0,truck,regcar,truck,van,truck,stwagon,methanol,methanol,cng,cng,electric,electric,3.53,3.53,1.93,1.93,2.25,2.25,125.0,125.0,300.0,300.0,250.0,250.0,6.0,6.0,2.5,2.5,4.0,4.0,85.0,85.0,140.0,140.0,85.0,85.0,0.00,0.00,0.25,0.25,0.60,0.60,2.0,2.0,3.0,3.0,3.0,3.0,0.7,0.7,1.0,1.0,1.0,1.0,1.0,1.0,4.0,4.0,6.0,6.0,0.0,0.0,0.7,0.7,0.1,0.1
4654,choice3,0.0,0.0,0.0,regcar,van,regcar,stwagon,regcar,truck,methanol,methanol,cng,cng,gasoline,gasoline,4.82,4.82,5.14,5.14,4.18,4.18,200.0,200.0,75.0,75.0,350.0,350.0,6.0,6.0,2.5,2.5,4.0,4.0,100.0,100.0,85.0,85.0,110.0,110.0,0.00,0.00,0.40,0.40,0.25,0.25,3.0,3.0,3.0,3.0,2.0,2.0,0.7,0.7,1.0,1.0,1.0,1.0,8.0,8.0,2.0,2.0,6.0,6.0,0.0,0.0,0.3,0.3,1.0,1.0

### Displaying Data Types

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4654 entries, 1 to 4654
Data columns (total 70 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   choice      4654 non-null   category
 1   college     4654 non-null   float64
 2   hsg2        4654 non-null   float64
 3   coml5       4654 non-null   float64
 4   type1       4654 non-null   category
 5   type2       4654 non-null   category
 6   type3       4654 non-null   category
 7   type4       4654 non-null   category
 8   type5       4654 non-null   category
 9   type6       4654 non-null   category
 10  fuel1       4654 non-null   category
 11  fuel2       4654 non-null   category
 12  fuel3       4654 non-null   category
 13  fuel4       4654 non-null   category
 14  fuel5       4654 non-null   category
 15  fuel6       4654 non-null   category
 16  price1      4654 non-null   float64
 17  price2      4654 non-null   float64
 18  price3      4654 non-null   float64
 19  price4      4654 non-null   float64
 20  price5      4654 non-null   float64
 21  price6      4654 non-null   float64
 22  range1      4654 non-null   float64
 23  range2      4654 non-null   float64
 24  range3      4654 non-null   float64
 25  range4      4654 non-null   float64
 26  range5      4654 non-null   float64
 27  range6      4654 non-null   float64
 28  acc1        4654 non-null   float64
 29  acc2        4654 non-null   float64
 30  acc3        4654 non-null   float64
 31  acc4        4654 non-null   float64
 32  acc5        4654 non-null   float64
 33  acc6        4654 non-null   float64
 34  speed1      4654 non-null   float64
 35  speed2      4654 non-null   float64
 36  speed3      4654 non-null   float64
 37  speed4      4654 non-null   float64
 38  speed5      4654 non-null   float64
 39  speed6      4654 non-null   float64
 40  pollution1  4654 non-null   float64
 41  pollution2  4654 non-null   float64
 42  pollution3  4654 non-null   float64
 43  pollution4  4654 non-null   float64
 44  pollution5  4654 non-null   float64
 45  pollution6  4654 non-null   float64
 46  size1       4654 non-null   float64
 47  size2       4654 non-null   float64
 48  size3       4654 non-null   float64
 49  size4       4654 non-null   float64
 50  size5       4654 non-null   float64
 51  size6       4654 non-null   float64
 52  space1      4654 non-null   float64
 53  space2      4654 non-null   float64
 54  space3      4654 non-null   float64
 55  space4      4654 non-null   float64
 56  space5      4654 non-null   float64
 57  space6      4654 non-null   float64
 58  cost1       4654 non-null   float64
 59  cost2       4654 non-null   float64
 60  cost3       4654 non-null   float64
 61  cost4       4654 non-null   float64
 62  cost5       4654 non-null   float64
 63  cost6       4654 non-null   float64
 64  station1    4654 non-null   float64
 65  station2    4654 non-null   float64
 66  station3    4654 non-null   float64
 67  station4    4654 non-null   float64
 68  station5    4654 non-null   float64
 69  station6    4654 non-null   float64
dtypes: category(13), float64(57)
memory usage: 2.1+ MB